data-xfer/main/default/objects/Object_Action__mdt/Object_Action__mdt.object-meta.xml
<CustomObject>
    <description>Holds information about how to perform a specific action (e.g. create, retrieve, update) a particular object in a particular data source.</description>
    <label>Object Action</label>
    <pluralLabel>Object Actions</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Action__mdt/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>get</fullName>
                <default>true</default>
                <label>get</label>
            </value>
            <value>
                <fullName>query</fullName>
            </value>
            <value>
                <fullName>create</fullName>
            </value>
            <value>
                <fullName>update</fullName>
            </value>
            <value>
                <fullName>delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/objects/Object_Action__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/classes/ExternalObjectAction.cls
public with sharing class ExternalObjectAction  extends ObjectWrapper {
    private final static Set<String> VALID_ACTIONS = new Set<String>{ 'get', 'query', 'create', 'update', 'delete' };

    public virtual class Selector extends ObjectWrapper.Selector {
        public Selector() { super(ExternalObjectAction.class); }
        public virtual override SObject getInstance(String name) { return Object_Action__mdt.getInstance(name); }
    }

    public static String getActionName(ExternalObject obj, String actionName) {
        if ((obj == null) || String.isBlank(actionName)) throw new IllegalArgumentException('External object and action name must be provided');
        if (!VALID_ACTIONS.contains(actionName)) throw new IllegalArgumentException('Invalid action: ' + actionName);
        return String.format('{0}_{1}', new List<Object>{ obj.getName(), actionName });

    }

    public static ExternalObjectAction getRecordByName(String name) {
        return (ExternalObjectAction)ObjectWrapper.getInstance(new Selector(), name);
    }

    public ExternalObjectAction() {}
        public ExternalObjectAction(Object_Action__mdt action) {
        super(action);
    }

    public String getAction() { return (String)this.get('Action__c'); }
    public String getMethod() { return (String)this.get('Method__c'); }
    public String getPath() { return (String)this.get('Path__c'); }
}