data-xfer/main/default/objects/Data_Flow_Definition__c/Data_Flow_Definition__c.object-meta.xml
<CustomObject>
    <label>Data Flow Definition</label>
    <nameField>
        <label>Data Flow Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Flow Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

data-xfer/main/default/objects/Data_Flow_Definition__c/fields/Data_Source_Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Data_Source_Instance_Name__c</fullName>
    <label>Data Source Instance Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Flow_Definition__c/fields/External_Data_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Data_Source__c</fullName>
    <label>External Data Source</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Flow_Definition__c/fields/External_Object__c.field-meta.xml
<CustomField>
    <fullName>External_Object__c</fullName>
    <label>External Object</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Flow_Definition__c/fields/Field_Mapping_Set__c.field-meta.xml
<CustomField>
    <fullName>Field_Mapping_Set__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Field Mapping Set</label>
    <referenceTo>Field_Mapping_Set__c</referenceTo>
    <relationshipLabel>Data Flow Definitions</relationshipLabel>
    <relationshipName>Data_Flow_Definitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

data-xfer/main/default/objects/Data_Flow_Definition__c/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <label>Salesforce Object</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Flow_Definition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>import</fullName>
            </value>
            <value>
                <fullName>export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/objects/Data_Transfer_Job__c/Data_Transfer_Job__c.object-meta.xml
<CustomObject>
    <label>Data Transfer Job</label>
    <nameField>
        <label>Data Transfer Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Transfer Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

data-xfer/main/default/objects/Data_Transfer_Job__c/fields/Data_Flow_Definition__c.field-meta.xml
<CustomField>
    <fullName>Data_Flow_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Data Flow Definition</label>
    <referenceTo>Data_Flow_Definition__c</referenceTo>
    <relationshipName>Data_Transfer_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

data-xfer/main/default/objects/Data_Transfer_Job__c/fields/Operation_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Operation_Timestamp__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Operation Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

data-xfer/main/default/objects/Data_Transfer_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/objects/Field_Mapping_Set__c/Field_Mapping_Set__c.object-meta.xml
<CustomObject>
    <label>Field Mapping Set</label>
    <nameField>
        <label>Field Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Mapping Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

data-xfer/main/default/classes/DataFlowDefinition.cls
public with sharing class DataFlowDefinition extends ObjectWrapper {
    protected DataSource source;
    protected DataSourceInstance dsi;
    protected ExternalObject exObj;
    protected ExternalObjectAction action;

    public static DataFlowDefinition getRecordById(Id recId) {
        if (String.isBlank(recId)) throw new IllegalArgumentException('Record id must be specified');
        Data_Flow_Definition__c dfd =
            [SELECT Id, Name, External_Object__c, Salesforce_Object__c, Type__c, External_Data_Source__c, Field_Mapping_Set__c, Data_Source_Instance_Name__c
             FROM Data_Flow_Definition__c WHERE Id=:recId];
        if (dfd != null) return new DataFlowDefinition(dfd);
        return null;
    }

    public DataFlowDefinition(Data_Flow_Definition__c dfd) {
        super(dfd);
    }

    public String getSourceApiName() { return (String)this.get('External_Data_Source__c'); }
    public String getExternalObjectApiName() { return (String)this.get('External_Object__c'); }
    public Boolean isImport() { return this.get('Type__c') == 'import'; }

    public DataSource getDataSource() {
        if (this.source == null){
            this.source = DataSource.getRecordByName(this.getSourceApiName());
        }
        return this.source;
    }

    public DataSourceInstance getDataSourceInstance() {
        if (this.dsi == null) {
            this.dsi = DataSourceInstance.getRecordByName((String)this.get('Data_Source_Instance_Name__c'));
        }
        return this.dsi;
    }

    public ExternalObject getExternalObject() {
        if (this.exObj == null){
            this.exObj = ExternalObject.getRecordByName(this.getExternalObjectApiName());
        }
        return this.exObj;
    }

    public ExternalObjectAction getDefaultAction() {
        if (this.action == null) {
            if (!this.isImport()) throw new IllegalArgumentException('No default action found');
            this.action = this.getAction('query');
        }
        return this.action;
    }

    public ExternalObjectAction getAction(String actionName) {
        String fullName = ExternalObjectAction.getActionName(this.getExternalObject(), actionName);
        return ExternalObjectAction.getRecordByName(fullName);
    }

    public void run() {
        DataSource ds = this.getDataSource();
        if (ds == null) throw new StandardException('Unable to find the data source for this data flow definition');
        ServiceHandler handler = ds.getHandler();
        handler.transferData(this);
    }

    public Datetime getLastRunTimestamp(Boolean successOnly)
    {
        Data_Transfer_Job__c lastJob;
        if (successOnly) {
            lastJob = [SELECT Id, Operation_Timestamp__c FROM Data_Transfer_Job__c WHERE Data_Flow_Definition__c=:this.record.Id AND Status__c='Succeeded' ORDER BY Operation_Timestamp__c DESC LIMIT 1];
        } else {
            lastJob = [SELECT Id, Operation_Timestamp__c FROM Data_Transfer_Job__c WHERE Data_Flow_Definition__c=:this.record.Id ORDER BY Operation_Timestamp__c DESC LIMIT 1];
        }
        if (lastJob != null) return lastJob.Operation_Timestamp__c;
        return null;
    }
}