data-xfer/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Used to hold information about a data object type in a data service.</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Field__mdt/Object_Field__mdt.object-meta.xml
<CustomObject>
    <label>Object Field</label>
    <pluralLabel>Object Fields</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Field__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>string</fullName>
                <default>true</default>
                <label>string</label>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>integer</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>reference</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/objects/Object_Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Object Fields</relationshipLabel>
    <relationshipName>Object_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

data-xfer/main/default/classes/ExternalObjectField.cls
public with sharing class ExternalObjectField extends ObjectWrapper {
    public virtual class Selector extends ObjectWrapper.Selector {
        public Selector() { super(ExternalObjectField.class); }
        public virtual override SObject getInstance(String name) { return Object_Field__mdt.getInstance(name); }
    }

    public static String getObjectName(ExternalObject obj, String fldName) {
        if ((obj == null) || String.isBlank(fldName)) throw new IllegalArgumentException('External object and field name must be provided');
        return String.format('{0}_{1}', new List<Object>{ obj.getName(), fldName });
    }

    public static ExternalObjectField getRecordByName(String name) {
        return (ExternalObjectField)ObjectWrapper.getInstance(new Selector(), name);
    }

    public static List<ExternalObjectField> queryByObjectName(String objName) {
        Selector sltr = new Selector();
        sltr.setQueryResults([SELECT DeveloperName, Display_Name__c, API_Name__c, Object__c, Data_Type__c, Options__c FROM Object_Field__mdt WHERE Object__r.DeveloperName=:objName]);
        return (List<ExternalObjectField>)ObjectWrapper.query(sltr);
    }

    public ExternalObjectField() {}
    public ExternalObjectField(Object_Field__mdt obj) {
            super(obj);
    }

    public String getName() { return (String)this.get('DeveloperName'); }
    public override String getApiName() { return (String)this.get('API_Name__c'); }
    public String getDisplayName() { return (String)this.get('Display_Name__c'); }
    public String getType() { return (String)this.get('Data_Type__c'); }
}