data-xfer/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Used to hold information about a data object type in a data service.</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Field__mdt/Object_Field__mdt.object-meta.xml
<CustomObject>
    <label>Object Field</label>
    <pluralLabel>Object Fields</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Field__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>string</fullName>
                <default>true</default>
                <label>string</label>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>integer</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>reference</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/objects/Object_Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Object Fields</relationshipLabel>
    <relationshipName>Object_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

data-xfer/main/default/classes/ExternalObjectFieldTest.cls
@isTest
public class ExternalObjectFieldTest {
    /************************************************************************/
    /*  Utility methods and classes
    /************************************************************************/
    public static Object_Field__mdt createExternalObjectField(String name, String apiName, String displayName, String objName, String dataType) {
        Map<String,Object> data = new Map<String,Object>{ 'DeveloperName' => name, 'API_Name__c' => apiName, 'Display_Name__c' => displayName, 'Object__c' => objName, 'Data_Type__c' => dataType };
        return (Object_Field__mdt)ObjectWrapperTest.createMetadataRecord(Object_Field__mdt.getSObjectType(), data);
    }

    public static void addTestExternalObjectField() {
        Object_Field__mdt fld_m = createExternalObjectField('svc_obj_fld', 'fld', 'Field', 'svc_obj', 'text');
        ObjectWrapper.addMock(new ObjectWrapperTest.TestSelector(ExternalObjectField.class, fld_m));
    }


    /************************************************************************/
    /*  Test methods
    /************************************************************************/
    @isTest
    static void testAccessors() {
        Object_Field__mdt fld_m = createExternalObjectField('svc_obj_fld', 'fld', 'Field', 'svc_obj', 'text');
        ExternalObjectField fld = new ExternalObjectField(fld_m);

        Test.startTest();
        {
            System.assertEquals('svc_obj_fld', fld.getName());
            System.assertEquals('fld', fld.getApiName());
            System.assertEquals('Field', fld.getDisplayName());
            System.assertEquals('text', fld.getType());
        }
        Test.stopTest();
    }

    @isTest
    static void testSelector() {
        // This test ensures the selector does not cause any errors but we don't assert the results of
        // any of the calls because we don't want to rely on certain data being present
        ExternalObjectField.getRecordByName('strp_inv_id');
        ExternalObjectField.queryByObjectName('strp_pi');
    }

    @isTest
    static void testGetActionName() {
        Object__mdt obj_m = ExternalObjectTest.createExternalObject('svc_obj', 'Object', 'obj', 'svc');
        ExternalObject obj = new ExternalObject(obj_m);

        System.assertEquals('svc_obj_query', ExternalObjectAction.getActionName(obj, 'query'));
        System.assertEquals('svc_obj_create', ExternalObjectAction.getActionName(obj, 'create'));

        Boolean isError = false;
        try {
            ExternalObjectAction.getActionName(obj, 'invalid');
        } catch (Exception ex) { isError = true; }
        System.assert(isError, 'Expected error from invalid action name but none thrown');
    }
}