data-xfer/main/default/objects/Object__mdt/Object__mdt.object-meta.xml
<CustomObject>
    <description>Used to hold information about a data object type in a data service.</description>
    <label>Object</label>
    <pluralLabel>Objects</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object__mdt/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <label>Data Source</label>
    <referenceTo>Data_Source__mdt</referenceTo>
    <relationshipLabel>Objects</relationshipLabel>
    <relationshipName>Objects</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

data-xfer/main/default/objects/Object_Action__mdt/Object_Action__mdt.object-meta.xml
<CustomObject>
    <description>Holds information about how to perform a specific action (e.g. create, retrieve, update) a particular object in a particular data source.</description>
    <label>Object Action</label>
    <pluralLabel>Object Actions</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Action__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Object Actions</relationshipLabel>
    <relationshipName>Object_Actions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

data-xfer/main/default/objects/Object_Field__mdt/Object_Field__mdt.object-meta.xml
<CustomObject>
    <label>Object Field</label>
    <pluralLabel>Object Fields</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Field__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>string</fullName>
                <default>true</default>
                <label>string</label>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>integer</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>reference</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

data-xfer/main/default/objects/Object_Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Object Fields</relationshipLabel>
    <relationshipName>Object_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-service/main/default/classes/SalesforceHandler.cls
public with sharing class SalesforceHandler extends ServiceHandler {
    public virtual class SalesforceObject extends ServiceObject {
        Schema.DescribeSobjectResult sObjDescribe;
        public SalesforceObject(Schema.DescribeSobjectResult obj) { this.sObjDescribe = obj; }
        public override String getApiName() { return this.sObjDescribe.getName(); }
        public override String getDisplayName() { return this.sObjDescribe.getLabel(); }
        public override List<ServiceObjectField> getFields() {
            // if (this.fields == null) {
            //     this.fields = new List<ServiceObjectField>();
            //     List<Object_Field__mdt> flds = [SELECT API_Name__c, Display_Name__c, Data_Type__c FROM Object_Field__mdt WHERE Object__c=:this.obj.Id];
            //     for (Object_Field__mdt fld : flds) {
            //         this.fields.add(new DefaultObjectField(fld));
            //     }
            // }
            // return this.fields;
            return null;
        }
    }

    public virtual class SalesforceObjectField extends ServiceObjectField {
        protected Object_Field__mdt field;

        public SalesforceObjectField(Object_Field__mdt fld) { this.field = fld; }
        public override String getApiName() { return this.field.API_Name__c; }
        public override String getDisplayName() { return this.field.Display_Name__c; }
        // TODO: need a map of our values to SFDC types
        public override String getType() { return this.field.Data_Type__c; }
    }

    public override List<ServiceObject> getAllObjects() {
        // There are so many standard sObjects in Salesforce that we still need to call out the most common, which are stored as
        // Object custom metadata records.

        // DataSource ds = DataSource.getRecordByName(this.getServiceApiName());
        // if (ds == null) throw new IllegalArgumentException('Unable to find a metadata record for the ' + this.getServiceDisplayName() + ' service');
        // List<Object__mdt> mdObjs = [SELECT API_Name__c, Display_Name__c, Data_Source__c FROM Object__mdt WHERE Data_Source__c=:ds.Id];
        // List<ServiceObject> objs = new List<ServiceObject>();
        // for (Object__mdt mdObj : mdObjs) {
        //     objs.add(new DefaultObject(mdObj));
        // }
        // return objs;
        return null;
    }

    public override ServiceObject getObject(String apiName) {
        // if (String.isBlank(apiName)) throw new IllegalArgumentException('A valid object name must be provided');
        // String mdName = getObjectName(apiName);
        // Object_mdt obj = Object__mdt.getInstance(mdName);
        // if (obj != null) return new DefaultObject(obj);
        return null;
    }

    public SalesforceHandler() {}

    public override String getServiceApiName() {
        return 'sfdc';
    }

    public override String getServiceDisplayName() {
        return 'Salesforce';
    }

    // public virtual ServiceResponse createResponse(HttpResponse resp) {
    //     return new StripeResponse(resp);
    // }

    // public override Map<String,String> getHeaders(Object_Action__mdt action) {
    //     Map<String,String> headers = new Map<String,String>();
    //     headers.put('Content-Type', 'application/json');
    //     return headers;
    // }
}