data-xfer/main/default/objects/Data_Source__mdt/Data_Source__mdt.object-meta.xml
<CustomObject>
    <description>Holds the basic information needed to connect to an external data source via web services.</description>
    <label>Data Source</label>
    <pluralLabel>Data Sources</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Data_Source__mdt/fields/Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_Url__c</fullName>
    <description>Holds the base URL (at least the protocol and server, possibly part of the path if it is invariant) to connect to the web service. It can potentially hold variables that the handler class will use to perform a substitution Variables should be of the format {{VARIABLE_NAME}}.</description>
    <label>Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source__mdt/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source__mdt/fields/Handler_Class__c.field-meta.xml
<CustomField>
    <fullName>Handler_Class__c</fullName>
    <label>Handler Class</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/classes/DataSource.cls
public with sharing virtual class DataSource extends ObjectWrapper {

    public static DataSource getRecordByName(String name) {
        if (String.isBlank(name)) throw new IllegalArgumentException('Name must be specified');
        Data_Source__mdt source = Data_Source__mdt.getInstance(name);
        if (source != null) return new DataSource(source);
        return null;
    }

    public DataSource(Data_Source__mdt src) {
        super(src);
    }

    public String getLabel() { return (String)this.get('Display_Name__c'); }
    public String getApiVersion() { return (String)this.get('API_Version__c'); }
    public String getBasePath() { return (String)this.get('Base_Url__c'); }
    public String getHandlerClass() { return (String)this.get('Handler_Class__c'); }

    public ServiceHandler getHandler() {
        String className = getHandlerClass();
        Object newObj = Type.forName(className).newInstance();
        if (!(newObj instanceof ServiceHandler)) throw new StandardException('Class "' + className + '" does not extend ServiceHandler');
        return (ServiceHandler)newObj;
    }
}