data-xfer/main/default/objects/Data_Source__mdt/Data_Source__mdt.object-meta.xml
<CustomObject>
    <description>Holds the basic information needed to connect to an external data source via web services.</description>
    <label>Data Source</label>
    <pluralLabel>Data Sources</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Data_Source__mdt/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source_Instance__c/Data_Source_Instance__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Data Source Instance</label>
</CustomObject>

data-xfer/main/default/objects/Data_Source_Instance__c/fields/API_Id__c.field-meta.xml
<CustomField>
    <fullName>API_Id__c</fullName>
    <label>API Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source_Instance__c/fields/Data_Source_Name__c.field-meta.xml
<CustomField>
    <fullName>Data_Source_Name__c</fullName>
    <externalId>true</externalId>
    <label>Data Source Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source_Instance__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source_Instance__c/fields/Instance_Type__c.field-meta.xml
<CustomField>
    <fullName>Instance_Type__c</fullName>
    <label>Instance Type</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/classes/DataSourceInstanceTest.cls
@isTest
public class DataSourceInstanceTest {
    /************************************************************************/
    /*  Utility methods and classes
    /************************************************************************/
    public static Data_Source_Instance__c createDataSourceInstance(String name, String dataSource, String instanceType) {
        return new Data_Source_Instance__c( Display_Name__c = name, Data_Source_Name__c = dataSource, Instance_Type__c = instanceType );
    }

    public static void addTestDataSource() {
        Data_Source_Instance__c inst_m = createDataSourceInstance('test', 'svc', 'production');
        ObjectWrapper.addMock(new ObjectWrapperTest.TestSelector(DataSourceInstance.class, inst_m));
    }


    /************************************************************************/
    /*  Test methods
    /************************************************************************/
    @isTest
    static void testAccessors() {
        Data_Source_Instance__c inst_m = new Data_Source_Instance__c( Display_Name__c = 'instance',
                                                                      Data_Source_Name__c = 'svc',
                                                                      Instance_Type__c = 'sandbox',
                                                                      API_Id__c = 'api_id',
                                                                      API_Secret__c = 'api_key',
                                                                      Options__c = '{ "key":"value" }' );
        DataSourceInstance inst = new DataSourceInstance(inst_m);

        // Create a mock to load the data source
        Data_Source__mdt ds_m = DataSourceTest.createDataSource('svc', 'TestDataSource', ServiceHandlerTest.ServiceHandlerMock.class.toString(), null, null);
        ObjectWrapper.addMock(new ObjectWrapperTest.TestSelector(DataSource.class, ds_m));

        Test.startTest();
        {
            System.assertEquals('instance', inst.getDisplayName());
            System.assertEquals('sandbox', inst.getInstanceType());
            System.assertEquals('api_id', inst.getApiId());
            System.assertEquals('api_key', inst.getApiSecret());

            DataSource src = inst.getDataSource();
            System.assertNotEquals(null, src);
            System.assertEquals('TestDataSource', src.getDisplayName());

            Map<String,Object> opts = inst.getOptions();
            System.assertNotEquals(null, opts);
            System.assertEquals(1, opts.size());
            System.assert(opts.containsKey('key'));
            System.assertEquals('value', opts.get('key'));

            inst_m.Options__c = 'key';
            Boolean isError = false;
            try {
                inst.getOptions();
            } catch (Exception e) { isError = true; }
            System.assert(isError, 'Expected a JSON error but not was thrown');
        }
        Test.stopTest();
    }

    @isTest
    static void testSelector() {
        // This test ensures the selector does not cause any errors but we don't assert the results of
        // any of the calls because we don't want to rely on certain data being present
        DataSourceInstance.getRecordByName('strp');
        DataSourceInstance.getAll();
        DataSourceInstance.queryByDataSourceName('svc');
    }
}