data-xfer/main/default/objects/Data_Source__mdt/Data_Source__mdt.object-meta.xml
<CustomObject>
    <description>Holds the basic information needed to connect to an external data source via web services.</description>
    <label>Data Source</label>
    <pluralLabel>Data Sources</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Data_Source__mdt/fields/Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_Url__c</fullName>
    <description>Holds the base URL (at least the protocol and server, possibly part of the path if it is invariant) to connect to the web service. It can potentially hold variables that the handler class will use to perform a substitution Variables should be of the format {{VARIABLE_NAME}}.</description>
    <label>Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source__mdt/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/objects/Data_Source__mdt/fields/Handler_Class__c.field-meta.xml
<CustomField>
    <fullName>Handler_Class__c</fullName>
    <label>Handler Class</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

data-xfer/main/default/classes/DataSourceTest.cls
@isTest
public class DataSourceTest {
    /************************************************************************/
    /*  Utility methods and classes
    /************************************************************************/
    public static Data_Source__mdt createDataSource(String name, String displayName, String handlerClass, String baseUrl, String apiVersion) {
        Map<String,Object> data = new Map<String,Object>{ 'DeveloperName' => name, 'Display_Name__c' => displayName, 'Handler_Class__c' => handlerClass, 'Base_Url__c' => baseUrl, 'API_Version__c' => apiVersion };
        return (Data_Source__mdt)ObjectWrapperTest.createMetadataRecord(Data_Source__mdt.getSObjectType(), data);
    }

    public static Data_Source__mdt addTestDataSource() {
        Data_Source__mdt ds_m = createDataSource('test', 'TestDataSource', ServiceHandlerTest.ServiceHandlerMock.class.toString(), 'https://test.com', '1');
        ObjectWrapper.addMock(new ObjectWrapperTest.TestSelector(DataSource.class, ds_m));
        return ds_m;
    }


    /************************************************************************/
    /*  Test methods
    /************************************************************************/
    @isTest
    static void testAccessors() {
        Data_Source__mdt ds_m = createDataSource('test', 'TestDataSource', ServiceHandlerTest.ServiceHandlerMock.class.toString(), 'https://test.com', '1');
        DataSource ds = new DataSource(ds_m);

        Test.startTest();
        {
            System.assertEquals('test', ds.getApiName());
            System.assertEquals('TestDataSource', ds.getDisplayName());
            System.assertEquals('https://test.com', ds.getBasePath());
            System.assertEquals('1', ds.getApiVersion());
            ServiceHandler handler = ds.getHandler();
            System.assertNotEquals(null, handler);
            System.assert(handler instanceof ServiceHandlerTest.ServiceHandlerMock);
        }
        Test.stopTest();
    }

    @isTest
    static void testSelector() {
        // This test ensures the selector does not cause any errors but we don't assert the results of
        // any of the calls because we don't want to rely on certain data being present
        DataSource.getRecordByName('strp');
        DataSource.getAll();
        DataSource.queryExternalSources();
    }
}