data-xfer/main/default/objects/Data_Source__mdt/Data_Source__mdt.object-meta.xml
<CustomObject>
    <description>Holds the basic information needed to connect to an external data source via web services.</description>
    <label>Data Source</label>
    <pluralLabel>Data Sources</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Action__mdt/Object_Action__mdt.object-meta.xml
<CustomObject>
    <description>Holds information about how to perform a specific action (e.g. create, retrieve, update) a particular object in a particular data source.</description>
    <label>Object Action</label>
    <pluralLabel>Object Actions</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Action__mdt/fields/Extras__c.field-meta.xml
<CustomField>
    <fullName>Extras__c</fullName>
    <description>A json representation of any relevant options</description>
    <label>Extras</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

data-xfer/main/default/objects/Object_Relation__mdt/Object_Relation__mdt.object-meta.xml
<CustomObject>
    <label>Object Relation</label>
    <pluralLabel>Object Relations</pluralLabel>
</CustomObject>

data-xfer/main/default/objects/Object_Relation__mdt/fields/Extras__c.field-meta.xml
<CustomField>
    <fullName>Extras__c</fullName>
    <label>Extras</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

stripe-service/main/default/classes/StripeHandlerTest.cls
@isTest
private class StripeHandlerTest {
    public static List<Object_Relation__mdt> getObjectRelations() {
        List<Object_Relation__mdt> rlns_m = new List<Object_Relation__mdt>();
        rlns_m.add(ObjectRelationTest.createObjectRelation('strp_p1_c1', 'strp', null, 'junction'));
        rlns_m.add(ObjectRelationTest.createObjectRelation('strp_p1_c2', 'strp', 'expand', null));
        rlns_m.add(ObjectRelationTest.createObjectRelation('strp_c2_g1', 'strp', 'expand', null));
        return rlns_m;
    }

    private static void addTestDataSource() {
        Data_Source__mdt ds_m = DataSourceTest.createDataSource('test', 'TestDataSource', StripeHandler.class.toString(), 'https://test.com', '1');
        ObjectWrapper.addMock(new ObjectWrapperTest.TestSelector(DataSource.class, ds_m));
    }

    public static void addObjectRelations() {
        Map<String,SObject> mapRels_m = new Map<String,SObject>();
        for (Object_Relation__mdt rel_m : getObjectRelations()) {
            mapRels_m.put(rel_m.DeveloperName, rel_m);
        }
        ObjectWrapper.addMock(new ObjectWrapperTest.TestSelector(ObjectRelation.class, mapRels_m));
    }

    public static String getTestConfigString() {
        // TODO: refine this
        return '{' +
        '"sourceSystem": "strp",' +
        '"sourceTree": {' +
        '  "objectName": "parent1",' +
        '  "childObjects": [{' +
        '    "objectName": "child1",' +
        '    "parentRelation": "strp_p1_c1",' +
        '    "childObjects": null' +
        '  },{' +
        '  "objectName": "child2",' +
        '  "parentRelation": "strp_p1_c2",' +
        '  "childObjects": [{' +
        '    "objectName": "grand1",' +
        '    "parentRelation": "strp_c2_g1",' +
        '    "childObjects": null' +
        '  }]' +
        '}]' +
        '}}';
    }

    @isTest
    static void testExpandParams() {
        // Setup
        addTestDataSource();
        DataSourceInstanceTest.addTestDataSourceInstance();
        addObjectRelations();
        ExternalObjectTest.addTestExternalObject();
        Object_Action__mdt actn_m = ExternalObjectActionTest.addTestExternalObjectAction();
        Configuration cfg = Configuration.fromString(getTestConfigString());
        DataTransfer.init(cfg);
        StripeHandler hdlr = (StripeHandler)DataTransfer.handler;

        Test.startTest();
        {
            List<String> expansions = hdlr.getExpansions(cfg);
            System.assertEquals(2, expansions.size());
            Set<String> expSet = new Set<String>(expansions);
            System.assert(expSet.contains('child2'));
            System.Assert(expSet.contains('child2.grand1'));

            // Set the prefix and ensure the expansions use it
            actn_m.Extras__c = '{ "resultsPrefix":"foo" }';
            expansions = hdlr.getExpansions(cfg);
            System.assertEquals(2, expansions.size());
            expSet = new Set<String>(expansions);
            System.assert(expSet.contains('foo.child2'));
            System.Assert(expSet.contains('foo.child2.grand1'));

            // Improperly set the prefix and ensure the expansions do not use it
            actn_m.Extras__c = '{ "resultPrefix":"foo" }';
            expansions = hdlr.getExpansions(cfg);
            System.assertEquals(2, expansions.size());
            expSet = new Set<String>(expansions);
            System.assert(expSet.contains('child2'));
            System.Assert(expSet.contains('child2.grand1'));
        }
        Test.stopTest();
    }
}